spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jiuyuan?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
 
mybatis:
  typeAliasesPackage: com.jiuyuan
  mapperLocations: classpath*:com/jiuyuan/*/mapper/*Mapper.xml 